global.noteskin_list = ["funkin", "pixel"]

global.noteskins = {

	funkin : {
		uigroup : "grp_noteskin_funkin",
		right : {
			note : note_funkin_right,
			strum : note_funkin_right_strum,
			tap : note_funkin_right_tap,
			press : note_funkin_right_press,
			hold : note_funkin_right_hold,
			holdcover : holdcover_funkin_right_idle,
			tail : tail_funkin_right,
			downtail : downtail_funkin_right,
			splash : [splash_funkin_right_0, splash_funkin_right_1],
			holdsplash : holdcover_funkin_right_end,
		},
		left : {
			note : note_funkin_left,
			strum : note_funkin_left_strum,
			tap : note_funkin_left_tap,
			press : note_funkin_left_press,
			hold : note_funkin_left_hold,
			holdcover : holdcover_funkin_left_idle,
			tail : tail_funkin_left,
			downtail : downtail_funkin_left,
			splash : [splash_funkin_left_0, splash_funkin_left_1],
			holdsplash : holdcover_funkin_left_end,
		},
		up : {
			note : note_funkin_up,
			strum : note_funkin_up_strum,
			tap : note_funkin_up_tap,
			press : note_funkin_up_press,
			hold : note_funkin_up_hold,
			holdcover : holdcover_funkin_up_idle,
			tail : tail_funkin_up,
			downtail : downtail_funkin_up,
			splash : [splash_funkin_up_0, splash_funkin_up_1],
			holdsplash : holdcover_funkin_up_end,
		},
		down : {
			note : note_funkin_down,
			strum : note_funkin_down_strum,
			tap : note_funkin_down_tap,
			press : note_funkin_down_press,
			hold : note_funkin_down_hold,
			holdcover : holdcover_funkin_down_idle,
			tail : tail_funkin_down,
			downtail : downtail_funkin_down,
			splash : [splash_funkin_down_0, splash_funkin_down_1],
			holdsplash : holdcover_funkin_down_end,
		},
	},
	
	pixel : {
		uigroup : "grp_noteskin_pixel",
		right : {
			note : note_pixel_right,
			strum : note_pixel_right_strum,
			tap : note_pixel_right_tap,
			press : note_pixel_right_press,
			hold : note_pixel_right_hold,
			holdcover : spr_blank,
			tail : tail_pixel_right,
			downtail : downtail_pixel_right,
			splash : [spr_blank, spr_blank],
			holdsplash : spr_blank,
		},
		left : {
			note : note_pixel_left,
			strum : note_pixel_left_strum,
			tap : note_pixel_left_tap,
			press : note_pixel_left_press,
			hold : note_pixel_left_hold,
			holdcover : spr_blank,
			tail : tail_pixel_left,
			downtail : downtail_pixel_left,
			splash : [spr_blank, spr_blank],
			holdsplash : spr_blank,
		},
		up : {
			note : note_pixel_up,
			strum : note_pixel_up_strum,
			tap : note_pixel_up_tap,
			press : note_pixel_up_press,
			hold : note_pixel_up_hold,
			holdcover : spr_blank,
			tail : tail_pixel_up,
			downtail : downtail_pixel_up,
			splash : [spr_blank, spr_blank],
			holdsplash : spr_blank,
		},
		down : {
			note : note_pixel_down,
			strum : note_pixel_down_strum,
			tap : note_pixel_down_tap,
			press : note_pixel_down_press,
			hold : note_pixel_down_hold,
			holdcover : spr_blank,
			tail : tail_pixel_down,
			downtail : downtail_pixel_down,
			splash : [spr_blank, spr_blank],
			holdsplash : spr_blank,
		},
	},
	
}