/*
If you want to add a new character, just copy the Testy segment of the struct
(Or whatever character you think will be most useful to build off of)
and replace the data as you need to. If you haven't done this before, I reccomend going through
the testy character data, as it has fully comments regarding how characters are formatted.
*/

global.characterdata = {

	testy : { // This character data is fully commented to make creating your own character easier.
		name : "Testy", // String to be shown for a characters name.
		animations : { // Animation list, add a struct to this struct to add an animation.
			idle : {
				name : "idle", // Animation name, string.
				path : spr_chr_bf_idle, // Animation path, reference the sprite.
				offsets : [0, 0], // Animation offsets, sorted as [X, Y].
				loops : false, // If true, animation will loop, if false, it will not, may be removed.
			},
			sing_left : {
				name : "left",
				path : spr_chr_bf_left,
				offsets : [0, 0],
				loops : false,
			},
			sing_down : {
				name : "down",
				path : spr_chr_bf_down,
				offsets : [0, 0],
				loops : false,
			},
			sing_up : {
				name : "up",
				path : spr_chr_bf_up,
				offsets : [0, 0],
				loops : false,
			},
			sing_right : {
				name : "right",
				path : spr_chr_bf_right,
				offsets : [0, 0],
				loops : false,
			},
		},
		texgroup : "bf",
		no_anti : false, // If true, character will not use antialiasing if it's enabled.
		gf_dance : false, // If true, character dances like GF. Used for GF, Nene, and Spooky Kids.
		position : [0, 0], // A sort of position offset for a character, added onto the stages character position.
		healthicon : "test", // The string to add to the end of an asset_get icon path.
		flip_x : false, // If true, the characters X scale will be flipped, flipping the character (obviously).
		health_color : [128, 128, 128], // The color of a characters healthbar, sorted as [R, G, B].
		camera_pos : [0, 0], // A camera offset based off of character instead of stage
		sing_length : 8, // The amount of time a character sings? Idrk what this one does either.
		scale : 1, // Pretty self explanitory. 
	},
	
	bf : {
		name : "Boyfriend",
		animations : {
			idle : {
				name : "idle",
				path : spr_chr_bf_idle,
				offsets : [0, 0],
				loops : false,
			},
			sing_left : {
				name : "left",
				path : spr_chr_bf_left,
				offsets : [-9, 8],
				loops : false,
			},
			sing_down : {
				name : "down",
				path : spr_chr_bf_down,
				offsets : [22, 52],
				loops : false,
			},
			sing_up : {
				name : "up",
				path : spr_chr_bf_up,
				offsets : [46, -30],
				loops : false,
			},
			sing_right : {
				name : "right",
				path : spr_chr_bf_right,
				offsets : [44, 4],	
				loops : false,
			},
			miss_left : {
				name : "miss_left",
				path : spr_chr_bf_left_miss,
				offsets : [-7, -18],
				loops : false,
			},
			miss_down : {
				name : "miss_down",
				path : spr_chr_bf_down_miss,
				offsets : [26, 21],
				loops : false,
			},
			miss_up : {
				name : "miss_up",
				path : spr_chr_bf_up_miss,
				offsets : [36, -29],
				loops : false,
			},
			miss_right : {
				name : "miss_right",
				path : spr_chr_bf_right_miss,
				offsets : [39, -25],
				loops : false,
			},
			hey : {
				name : "hey",
				path : spr_chr_bf_hey,
				offsets : [-1, -6],
				loops : false,
			},
			scared : {
				name : "scared",
				path : spr_chr_bf_scared,
				offsets : [0, 0],
				loops : false,
			},
			cheer : {
				name : "cheer",
				path : spr_chr_bf_cheer,
				offsets : [9, -65],
				loops : false,
			},
		},
		texgroup : "bf",
		no_anti : false,
		gf_dance : false,
		position : [0, 350],
		healthicon : "bf",
		flip_x : false,
		health_color : [49, 176, 209],
		camera_pos : [0, 0],
		sing_length : 8,
		scale : 1,
	},
	
	dad : {
		name : "Daddy Dearest",
		animations : {
			idle : {
				name : "idle",
				path : spr_chr_dad_idle,
				offsets : [0, 0],
				hold_indices : [11, 13], // ONLY INCLUDE IF CHARACTER HAS ANIMATED HOLD NOTE
				loops : false,
			},
			sing_left : {
				name : "left",
				path : spr_chr_dad_right,
				offsets : [6, -12],
				hold_indices : [3, 16],
				loops : false,
			},
			sing_down : {
				name : "down",
				path : spr_chr_dad_down,
				offsets : [-1, 31],
				hold_indices : [3, 16],
				loops : false,
			},
			sing_up : {
				name : "up",
				path : spr_chr_dad_up,
				offsets : [11, -53],
				hold_indices : [3, 16],
				loops : false,
			},
			sing_right : {
				name : "right",
				path : spr_chr_dad_left,
				offsets : [2, -28],
				hold_indices : [3, 16],
				loops : false,
			},
		},
		texgroup : "dad",
		no_anti : false,
		gf_dance : false,
		position : [0, 0],
		healthicon : "dad",
		flip_x : false,
		health_color : [175, 102, 206],
		camera_pos : [0, 0],
		sing_length : 8,
		scale : 1,
	},
	
	gf : {
		name : "Girlfriend",
		animations : {
			idle : {
				name : "idle",
				path : spr_chr_gf_idle,
				offsets : [0, 0],
				loops : false,
			},
			scared : {
				name : "scared",
				path : spr_chr_gf_scared,
				offsets : [2, 7],
				loops : false,
			},
		},
		texgroup : "gf",
		no_anti : false,
		gf_dance : true,
		position : [0, 0],
		healthicon : "gf",
		flip_x : false,
		health_color : [165, 0, 77],
		camera_pos : [0, 0],
		sing_length : 8,
		scale : 1,
	},
	
	pico : {
		name : "Pico",
		animations : {
			idle : {
				name : "idle",
				path : spr_chr_pico_idle,
				offsets : [0, 0],
				loops : false,
			},
			sing_left : {
				name : "left",
				path : spr_chr_pico_right,
				offsets : [-49, 0],
				loops : false,
			},
			sing_down : {
				name : "down",
				path : spr_chr_pico_down,
				offsets : [89, 83],
				loops : false,
			},
			sing_up : {
				name : "up",
				path : spr_chr_pico_up,
				offsets : [25, -33],
				loops : false,
			},
			sing_right : {
				name : "right",
				path : spr_chr_pico_left,
				offsets : [82, 11],
				loops : false,
			},
		},
		texgroup : "pico",
		no_anti : false,
		gf_dance : false,
		position : [400, 300],
		healthicon : "pico",
		flip_x : true,
		health_color : [183, 216, 85],
		camera_pos : [-452, 0],
		sing_length : 8,
		scale : 1,
	},
		
	darnell : {
		name : "Darnell",
		animations : {
			idle : {
				name : "idle",
				path : spr_chr_darnell_idle,
				offsets : [0, 0],
				loops : false,
			},
			sing_left : {
				name : "left",
				path : spr_chr_darnell_left,
				offsets : [2, 0],
				hold_indices : [5, 12],
				loops : false,
			},
			sing_down : {
				name : "down",
				path : spr_chr_darnell_down,
				offsets : [-15, -12],
				hold_indices : [5, 12],
				loops : false,
			},
			sing_up : {
				name : "up",
				path : spr_chr_darnell_up,
				offsets : [1, -5],
				hold_indices : [5, 12],
				loops : false,
			},
			sing_right : {
				name : "right",
				path : spr_chr_darnell_right,
				offsets : [-3, -3],
				hold_indices : [5, 12],
				loops : false,
			},
			light_can : {
				name : "light_can",
				path : spr_chr_darnell_canlight,
				offsets : [72, 119],
				loops : false,
			},
			kick : {
				name : "kick",
				path : spr_chr_darnell_kickup,
				offsets : [-10, -17],
				loops : false,
			},
			knee : {
				name : "knee",
				path : spr_chr_darnell_knee,
				offsets : [-19, -13],
				loops : false,
			},
			laugh : {
				name : "laugh",
				path : spr_chr_darnell_laugh,
				offsets : [-2, -1],
				loops : false,
			},
			pissed : {
				name : "pissed",
				path : spr_chr_darnell_pissed,
				offsets : [0, 0],
				loops : false,
			},
		},
		texgroup : "darnell",
		no_anti : false,
		gf_dance : false,
		position : [0, 0],
		healthicon : "darnell",
		flip_x : false,
		health_color : [95, 85, 142],
		camera_pos : [0, 0],
		sing_length : 8,
		scale : 1,
	},
		
	pico_playable : {
		name : "Pico Playable",
		animations : {
			idle : {
				name : "idle",
				path : spr_chr_pico_idle,
				offsets : [0, 0],
				loops : false,
			},
			sing_left : {
				name : "left",
				path : spr_chr_pico_left,
				offsets : [-82, 11],
				loops : false,
			},
			sing_down : {
				name : "down",
				path : spr_chr_pico_down,
				offsets : [-103, 84],
				loops : false,
			},
			sing_up : {
				name : "up",
				path : spr_chr_pico_up,
				offsets : [-17, -36],
				loops : false,
			},
			sing_right : {
				name : "right",
				path : spr_chr_pico_right,
				offsets : [54, -1],
				loops : false,
			},
			miss_left : {
				name : "miss_left",
				path : spr_chr_pico_left_miss,
				offsets : [-80, -28],
				loops : false,
			},
			miss_down : {
				name : "miss_down",
				path : spr_chr_pico_down_miss,
				offsets : [-98, 40],
				loops : false,
			},
			miss_up : {
				name : "miss_up",
				path : spr_chr_pico_up_miss,
				offsets : [-20, -76],
				loops : false,
			},
			miss_right : {
				name : "miss_right",
				path : spr_chr_pico_right_miss,
				offsets : [50, -49],
				loops : false,
			},
		},
		texgroup : "pico",
		no_anti : false,
		gf_dance : false,
		position : [0, 325],
		healthicon : "pico",
		flip_x : false,
		health_color : [183, 216, 85],
		camera_pos : [0, 0],
		sing_length : 8,
		scale : 1,
	},
		
	nene : {
		name : "Nene",
		animations : {
			idle : {
				name : "idle",
				path : spr_chr_nene_idle,
				offsets : [0, 0],
				loops : false,
			},
		},
		texgroup : "nene",
		no_anti : false,
		gf_dance : true,
		position : [0, 0],
		healthicon : "nene",
		flip_x : false,
		health_color : [165, 0, 77],
		camera_pos : [0, 0],
		sing_length : 8,
		scale : 1,
	},
		
	starved : {
		name : "Starved Eggman",
		animations : {
			idle : {
				name : "idle",
				path : spr_chr_starved_idle,
				offsets : [0, 0],
				loops : false,
			},
			sing_left : {
				name : "left",
				path : spr_chr_starved_left,
				offsets : [-188, 79],
				loops : false,
			},
			sing_down : {
				name : "down",
				path : spr_chr_starved_down,
				offsets : [-122, 147],
				loops : false,
			},
			sing_up : {
				name : "up",
				path : spr_chr_starved_up,
				offsets : [-43, -129],
				loops : false,
			},
			sing_right : {
				name : "right",
				path : spr_chr_starved_right,
				offsets : [24, 79],
				loops : false,
			},
		},
		texgroup : "starved",
		no_anti : false,
		gf_dance : false,
		position : [0, 0],
		healthicon : "starved",
		flip_x : false,
		health_color : [255, 0, 0],
		camera_pos : [0, 0],
		sing_length : 8,
		scale : 1,
	},
	
	monster : {
		name : "Monster",
		animations : {
			idle : {
				name : "idle",
				path : spr_chr_monster_idle,
				offsets : [0, 0],
				loops : false,
			},
			sing_left : {
				name : "left",
				path : spr_chr_monster_left,
				offsets : [50, -14],
				loops : false,
			},
			sing_down : {
				name : "down",
				path : spr_chr_monster_down,
				offsets : [50, 84],
				loops : false,
			},
			sing_up : {
				name : "up",
				path : spr_chr_monster_up,
				offsets : [29, -93],
				loops : false,
			},
			sing_right : {
				name : "right",
				path : spr_chr_monster_right,
				offsets : [33, -10],
				loops : false,
			},
		},
		texgroup : "monster",
		no_anti : false,
		gf_dance : false,
		position : [50, 150],
		healthicon : "monster",
		flip_x : false,
		health_color : [243, 255, 110],
		camera_pos : [-150, -75],
		sing_length : 8,
		scale : 1,
	},
		
	spooky : {
		name : "Spooky Kids",
		animations : {
			idle : {
				name : "idle",
				path : spr_chr_spooky_idle,
				offsets : [0, 0],
				loops : false,
			},
			sing_left : {
				name : "left",
				path : spr_chr_spooky_left,
				offsets : [-133, 15],
				loops : false,
			},
			sing_down : {
				name : "down",
				path : spr_chr_spooky_down,
				offsets : [50, 153],
				loops : false,
			},
			sing_up : {
				name : "up",
				path : spr_chr_spooky_up,
				offsets : [28, -24],
				loops : false,
			},
			sing_right : {
				name : "right",
				path : spr_chr_spooky_right,
				offsets : [151, 11],
				loops : false,
			},
			cheer : {
				name : "cheer",
				path : spr_chr_spooky_cheer,
				offsets : [-48, -30],
				loops : false,
			},
		},
		texgroup : "spooky",
		no_anti : false,
		gf_dance : true,
		position : [0, 200],
		healthicon : "spooky",
		flip_x : false,
		health_color : [213, 126, 0],
		camera_pos : [0, 0],
		sing_length : 8,
		scale : 1,
	},
		
	mom_car : {
		name : "Mommy Mearest (Car)",
		animations : {
			idle : {
				name : "idle",
				path : spr_chr_momcar_idle,
				offsets : [0, 0],
				hold_indices : [10, 13], // ONLY INCLUDE IF CHARACTER HAS ANIMATED HOLD NOTE
				loops : false,
			},
			sing_left : {
				name : "left",
				path : spr_chr_momcar_left,
				offsets : [-80, 0],
				hold_indices : [3, 10],
				loops : false,
			},
			sing_down : {
				name : "down",
				path : spr_chr_momcar_down,
				offsets : [11, 157],
				hold_indices : [3, 15],
				loops : false,
			},
			sing_up : {
				name : "up",
				path : spr_chr_momcar_up,
				offsets : [4, -82],
				hold_indices : [3, 15],
				loops : false,
			},
			sing_right : {
				name : "right",
				path : spr_chr_momcar_right,
				offsets : [26, 36],
				hold_indices : [3, 10],
				loops : false,
			},
		},
		texgroup : "momcar",
		no_anti : false,
		gf_dance : false,
		position : [0, 0],
		healthicon : "mom",
		flip_x : false,
		health_color : [216, 85, 142],
		camera_pos : [0, 0],
		sing_length : 8,
		scale : 1,
	},
		
	bf_car : {
		name : "Boyfriend (Car)",
		animations : {
			idle : {
				name : "idle",
				path : spr_chr_bfcar_idle,
				offsets : [0, 0],
				hold_indices : [9, 14],
				loops : false,
			},
			sing_left : {
				name : "left",
				path : spr_chr_bfcar_left,
				offsets : [-9, 8],
				hold_indices : [3, 16],
				loops : false,
			},
			sing_down : {
				name : "down",
				path : spr_chr_bfcar_down,
				offsets : [22, 52],
				hold_indices : [3, 16],
				loops : false,
			},
			sing_up : {
				name : "up",
				path : spr_chr_bfcar_up,
				offsets : [46, -30],
				hold_indices : [3, 15],
				loops : false,
			},
			sing_right : {
				name : "right",
				path : spr_chr_bfcar_right,
				offsets : [44, 4],
				hold_indices : [3, 16],
				loops : false,
			},
			miss_left : {
				name : "miss_left",
				path : spr_chr_bfcar_left_miss,
				offsets : [-7, -18],
				loops : false,
			},
			miss_down : {
				name : "miss_down",
				path : spr_chr_bfcar_down_miss,
				offsets : [26, 21],
				loops : false,
			},
			miss_up : {
				name : "miss_up",
				path : spr_chr_bfcar_up_miss,
				offsets : [36, -29],
				loops : false,
			},
			miss_right : {
				name : "miss_right",
				path : spr_chr_bfcar_right_miss,
				offsets : [39, -25],
				loops : false,
			},
		},
		texgroup : "bfcar",
		no_anti : false,
		gf_dance : false,
		position : [0, 350],
		healthicon : "bf",
		flip_x : false,
		health_color : [49, 176, 209],
		camera_pos : [0, 0],
		sing_length : 8,
		scale : 1,
	},
		
	gf_car : {
		name : "Girlfriend (Car)",
		animations : {
			idle : {
				name : "idle",
				path : spr_chr_gfcar_idle,
				offsets : [0, 0],
				loops : false,
			},
		},
		texgroup : "gfcar",
		no_anti : false,
		gf_dance : true,
		position : [0, 0],
		healthicon : "gf",
		flip_x : false,
		health_color : [165, 0, 77],
		camera_pos : [0, 0],
		sing_length : 8,
		scale : 1,
	},
		
	parents_christmas : {
		name : "Parents (Christmas)",
		animations : { 
			idle : {
				name : "idle", 
				path : spr_chr_parents_idle,
				offsets : [0, 0],
				loops : false,
			},
			sing_left : {
				name : "left",
				path : spr_chr_parents_left,
				offsets : [28, -20],
				loops : false,
			},
			sing_down : {
				name : "down",
				path : spr_chr_parents_down,
				offsets : [26, 24],
				loops : false,
			},
			sing_up : {
				name : "up",
				path : spr_chr_parents_up,
				offsets : [50, -25],
				loops : false,
			},
			sing_right : {
				name : "right",
				path : spr_chr_parents_right,
				offsets : [0, 18],
				loops : false,
			},
			sing_left_mom : {
				name : "left_mom",
				path : spr_chr_parents_left_mom,
				offsets : [28, -19],
				loops : false,
			},
			sing_down_mom : {
				name : "down_mom",
				path : spr_chr_parents_down_mom,
				offsets : [27, 23],
				loops : false,
			},
			sing_up_mom : {
				name : "up_mom",
				path : spr_chr_parents_up_mom,
				offsets : [50, -29],
				loops : false,
			},
			sing_right_mom : {
				name : "right_mom",
				path : spr_chr_parents_right_mom,
				offsets : [0, 18],
				loops : false,
			},
		},
		texgroup : "parents",
		no_anti : false,
		gf_dance : false,
		position : [0, 0],
		healthicon : "parents",
		flip_x : false,
		health_color : [196, 94, 174],
		camera_pos : [0, 0],
		sing_length : 8,
		scale : 1,
	},
		
	gf_christmas : {
		name : "Girlfriend (Christmas)",
		animations : {
			idle : {
				name : "idle",
				path : spr_chr_gfchristmas_idle,
				offsets : [0, 0],
				loops : false,
			},
		},
		texgroup : "gfchristmas",
		no_anti : false,
		gf_dance : true,
		position : [0, 0],
		healthicon : "gf",
		flip_x : false,
		health_color : [165, 0, 77],
		camera_pos : [0, 0],
		sing_length : 8,
		scale : 1,
	},
		
	bf_christmas : {
		name : "Boyfriend (Christmas)",
		animations : {
			idle : {
				name : "idle",
				path : spr_chr_bfchristmas_idle,
				offsets : [0, 0],
				loops : false,
			},
			sing_left : {
				name : "left",
				path : spr_chr_bfchristmas_left,
				offsets : [-9, 8],
				loops : false,
			},
			sing_down : {
				name : "down",
				path : spr_chr_bfchristmas_down,
				offsets : [22, 52],
				loops : false,
			},
			sing_up : {
				name : "up",
				path : spr_chr_bfchristmas_up,
				offsets : [46, -30],
				loops : false,
			},
			sing_right : {
				name : "right",
				path : spr_chr_bfchristmas_right,
				offsets : [44, 4],
				loops : false,
			},
			miss_left : {
				name : "miss_left",
				path : spr_chr_bfchristmas_left_miss,
				offsets : [-7, -18],
				loops : false,
			},
			miss_down : {
				name : "miss_down",
				path : spr_chr_bfchristmas_down_miss,
				offsets : [26, 21],
				loops : false,
			},
			miss_up : {
				name : "miss_up",
				path : spr_chr_bfchristmas_up_miss,
				offsets : [36, -29],
				loops : false,
			},
			miss_right : {
				name : "miss_right",
				path : spr_chr_bfchristmas_right_miss,
				offsets : [39, -25],
				loops : false,
			},
		},
		texgroup : "bfchristmas",
		no_anti : false,
		gf_dance : false,
		position : [0, 350],
		healthicon : "bf",
		flip_x : false,
		health_color : [49, 176, 209],
		camera_pos : [0, 0],
		sing_length : 8,
		scale : 1,
	},
		
	monster_christmas : {
		name : "Monster (Christmas)",
		animations : {
			idle : {
				name : "idle",
				path : spr_chr_monsterchristmas_idle,
				offsets : [0, 0],
				loops : false,
			},
			sing_right : {
				name : "right",
				path : spr_chr_monsterchristmas_left,
				offsets : [34, -11],
				hold_indices : [7, 16],
				loops : false,
			},
			sing_down : {
				name : "down",
				path : spr_chr_monsterchristmas_down,
				offsets : [50, 91],
				hold_indices : [7, 16],
				loops : false,
			},
			sing_up : {
				name : "up",
				path : spr_chr_monsterchristmas_up,
				offsets : [28, -56],
				hold_indices : [9, 16],
				loops : false,
			},
			sing_left : {
				name : "left",
				path : spr_chr_monsterchristmas_right,
				offsets : [53, -8],
				hold_indices : [7, 16],
				loops : false,
			},
		},
		texgroup : "monsterchristmas",
		no_anti : false,
		gf_dance : false,
		position : [0, 0],
		healthicon : "monster",
		flip_x : false,
		health_color : [243, 255, 110],
		camera_pos : [-150, -75],
		sing_length : 8,
		scale : 1,
	},
		
	tankman : {
		name : "Tankman",
		animations : {
			idle : {
				name : "idle",
				path : spr_chr_tankman_idle,
				offsets : [0, 0],
				loops : false,
			},
			sing_left : {
				name : "left",
				path : spr_chr_tankman_left,
				offsets : [-22, 13],
				loops : false,
			},
			sing_down : {
				name : "down",
				path : spr_chr_tankman_down,
				offsets : [60, 104],
				loops : false,
			},
			sing_up : {
				name : "up",
				path : spr_chr_tankman_up,
				offsets : [24, -53],
				loops : false,
			},
			sing_right : {
				name : "right",
				path : spr_chr_tankman_right,
				offsets : [85, 28],
				loops : false,
			},
		},
		texgroup : "tankman",
		no_anti : false,
		gf_dance : false,
		position : [0, 0],
		healthicon : "tankman",
		flip_x : true,
		health_color : [255, 255, 255],
		camera_pos : [-431, 0],
		sing_length : 8,
		scale : 1,
	},
		
	gf_tank : {
		name : "Girlfriend (Tankman)",
		animations : {
			idle : {
				name : "idle",
				path : spr_chr_gftank_idle,
				offsets : [0, 0],
				loops : false,
			},
		},
		texgroup : "gftank",
		no_anti : false,
		gf_dance : true,
		position : [0, 0],
		healthicon : "gf",
		flip_x : false,
		health_color : [165, 0, 77],
		camera_pos : [0, 0],
		sing_length : 8,
		scale : 1,
	},
		
	bf_pixel : {
		name : "Boyfriend (Pixel)",
		animations : {
			idle : {
				name : "idle",
				path : spr_chr_bfpixel_idle,
				offsets : [0, 0],
				hold_indices : [9, 14],
				loops : false,
			}
		},
		texgroup : "bfpixel",
		no_anti : true,
		gf_dance : false,
		position : [0, 0],
		healthicon : "bf_pixel",
		flip_x : false,
		health_color : [49, 176, 209],
		camera_pos : [0, 0],
		sing_length : 8,
		scale : 6,
	},
		
	bf_dark : {
		name : "Boyfriend (Dark)",
		animations : {
			idle : {
				name : "idle",
				path : spr_chr_bfdark_idle,
				offsets : [0, 0],
				loops : false,
			},
			sing_left : {
				name : "left",
				path : spr_chr_bfdark_left,
				offsets : [-9, 8],
				loops : false,
			},
			sing_down : {
				name : "down",
				path : spr_chr_bfdark_down,
				offsets : [22, 52],
				loops : false,
			},
			sing_up : {
				name : "up",
				path : spr_chr_bfdark_up,
				offsets : [46, -30],
				loops : false,
			},
			sing_right : {
				name : "right",
				path : spr_chr_bfdark_right,
				offsets : [44, 4],	
				loops : false,
			},
			miss_left : {
				name : "miss_left",
				path : spr_chr_bfdark_left_miss,
				offsets : [-7, -18],
				loops : false,
			},
			miss_down : {
				name : "miss_down",
				path : spr_chr_bfdark_down_miss,
				offsets : [26, 21],
				loops : false,
			},
			miss_up : {
				name : "miss_up",
				path : spr_chr_bfdark_up_miss,
				offsets : [36, -29],
				loops : false,
			},
			miss_right : {
				name : "miss_right",
				path : spr_chr_bfdark_right_miss,
				offsets : [39, -25],
				loops : false,
			},
			hey : {
				name : "hey",
				path : spr_chr_bfdark_hey,
				offsets : [-1, -6],
				loops : false,
			},
			scared : {
				name : "scared",
				path : spr_chr_bfdark_scared,
				offsets : [0, 0],
				loops : false,
			},
		},
		texgroup : "bfdark",
		no_anti : false,
		gf_dance : false,
		position : [0, 350],
		healthicon : "bf",
		flip_x : false,
		health_color : [49, 176, 209],
		camera_pos : [0, 0],
		sing_length : 8,
		scale : 1,
	},
	
	gf_dark : {
		name : "Girlfriend (Dark)",
		animations : {
			idle : {
				name : "idle",
				path : spr_chr_gfdark_idle,
				offsets : [0, 0],
				loops : false,
			},
			scared : {
				name : "scared",
				path : spr_chr_gfdark_scared,
				offsets : [2, 7],
				loops : false,
			},
		},
		texgroup : "gfdark",
		no_anti : false,
		gf_dance : true,
		position : [0, 0],
		healthicon : "gf",
		flip_x : false,
		health_color : [165, 0, 77],
		camera_pos : [0, 0],
		sing_length : 8,
		scale : 1,
	},
		
	spooky_dark : {
		name : "Spooky Kids (Dark)",
		animations : {
			idle : {
				name : "idle",
				path : spr_chr_spookydark_idle,
				offsets : [0, 0],
				loops : false,
			},
			sing_left : {
				name : "left",
				path : spr_chr_spookydark_left,
				offsets : [-133, 15],
				loops : false,
			},
			sing_down : {
				name : "down",
				path : spr_chr_spookydark_down,
				offsets : [50, 153],
				loops : false,
			},
			sing_up : {
				name : "up",
				path : spr_chr_spookydark_up,
				offsets : [28, -24],
				loops : false,
			},
			sing_right : {
				name : "right",
				path : spr_chr_spookydark_right,
				offsets : [151, 11],
				loops : false,
			},
			cheer : {
				name : "cheer",
				path : spr_chr_spookydark_cheer,
				offsets : [-48, -30],
				loops : false,
			},
		},
		texgroup : "spookydark",
		no_anti : false,
		gf_dance : true,
		position : [0, 200],
		healthicon : "spooky",
		flip_x : false,
		health_color : [213, 126, 0],
		camera_pos : [0, 0],
		sing_length : 8,
		scale : 1,
	},
		
	nene_dark : {
		name : "Nene (Dark)",
		animations : {
			idle : {
				name : "idle",
				path : spr_chr_nenedark_idle,
				offsets : [136, 0],
				loops : false,
			},
		},
		texgroup : "nenedark",
		no_anti : false,
		gf_dance : true,
		position : [0, 0],
		healthicon : "nene",
		flip_x : false,
		health_color : [165, 0, 77],
		camera_pos : [0, 0],
		sing_length : 8,
		scale : 1,
	},
		
	pico_dark : {
		name : "Pico Playable (Dark)",
		animations : {
			idle : {
				name : "idle",
				path : spr_chr_picodark_idle,
				offsets : [0, 0],
				loops : false,
			},
			sing_left : {
				name : "left",
				path : spr_chr_picodark_left,
				offsets : [-82, 11],
				loops : false,
			},
			sing_down : {
				name : "down",
				path : spr_chr_picodark_down,
				offsets : [-103, 84],
				loops : false,
			},
			sing_up : {
				name : "up",
				path : spr_chr_picodark_up,
				offsets : [-17, -36],
				loops : false,
			},
			sing_right : {
				name : "right",
				path : spr_chr_picodark_right,
				offsets : [54, -1],
				loops : false,
			},
			miss_left : {
				name : "miss_left",
				path : spr_chr_picodark_left_miss,
				offsets : [-80, -28],
				loops : false,
			},
			miss_down : {
				name : "miss_down",
				path : spr_chr_picodark_down_miss,
				offsets : [-98, 40],
				loops : false,
			},
			miss_up : {
				name : "miss_up",
				path : spr_chr_picodark_up_miss,
				offsets : [-20, -76],
				loops : false,
			},
			miss_right : {
				name : "miss_right",
				path : spr_chr_picodark_right_miss,
				offsets : [50, -49],
				loops : false,
			},
		},
		texgroup : "picodark",
		no_anti : false,
		gf_dance : false,
		position : [0, 325],
		healthicon : "pico",
		flip_x : false,
		health_color : [183, 216, 85],
		camera_pos : [0, 0],
		sing_length : 8,
		scale : 1,
	},
	
}